FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
ARG PROJECT
RUN dotnet restore "$PROJECT/$PROJECT.csproj"
RUN dotnet publish "$PROJECT/$PROJECT.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
ARG PROJECT
ENV PROJECT=$PROJECT
COPY --from=build /app/publish .
ENTRYPOINT dotnet ${PROJECT}.dll
